work on action

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -13,16 +13,14 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v2
 
-    - name: Configure Git with PAT
+    - name: Set up Git with PAT
       run: |
-        git config --global user.name 'GitHub Actions'
-        git config --global user.email 'actions@github.com'
         git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n x-access-token:${{ secrets.GH_PAT }} | base64)"
 
     - name: Delete existing tag
       run: |
-        git push --delete origin v1
-        git tag --delete v1
+        git push --delete origin v1 || echo "Tag v1 not found."
+        git tag --delete v1 || echo "Local tag v1 not found."
 
     - name: Create new tag
       run: |
